== Chapter 13: Conclusion
:imagesdir: images

=== To learn more

NOTE:: If you are interested in what you are interested in, you can send requests to the issue that you want to know more, or reply with twitter. Also recommended suggestions are saved.


==== Those who want to learn more machine learning


You should aim to be able to read through link:https://www.microsoft.com/en-us/research/people/cmbishop/#!prml-book[Pattern Recognition and Machine Learning(PRML)]. The PDF can be downloaded for free.

If you find that PRML is tough, you may find it easier to search for "before reading PRML" etc. so you should choose the one that suits you.


==== Want to learn more about Chemoinformatics from IT

Since this book focuses on AI drug discovery, it explains the basics of machine learning and analysis methods, but chemoinformatics is, like bioinformatics, an efficient way of expressing molecules and data. It also includes storage methods and fast search technology. If you are interested in chemoinformatics as such informatics (IT aspect), it is recommended to read more from link:https://www.amazon.co.jp/Chemoinformatics-Basic-Concepts-Methods-English-ebook/dp/B07MMWKNSL/[Chemoinformatics: Basic Concepts and Methods] and dig deeper on topics of interest.

==== For a deeper understanding of medicinal chemistry and chemoinformatics

If you belong to the pharmacokinetics, toxicity, or pharmacology of a pharmaceutical company or academia and want to know the point of this book by all means , we recommend that you read link:https://www.amazon.co.jp/Drug-Like-Properties-Concepts-Structure-Optimization-ebook/dp/B019OMDRU4/[Drug-Like Properties: Concepts, Structure Design and Methods from ADME to Toxicity Optimization]. You This is a text that is generally read by new employees who are assigned to the synthesis department of a pharmaceutical company, so it would be fun for anyone who has read this book. If there is a part that I can not catch up with, I can go over the related books, and I think it is good to learn further from this book as a clue.

In addition, people who are involved in pharmacokinetics should be able to use it as a strength in link:https://www.amazon.co.jp/Physiologically-Based-Pharmacokinetic-PBPK-Modeling-Simulations-ebook/dp/B007BGZKWO/[PBPK modeling] if they can understand QSAR / QSPR in this document . Since optimization of kinetic profiles is very important for drug differentiation strategies, it may be very useful to have strong QSPR + PBPK.

==== If you want to be a drug designer

Although this book has introduced informatics methods based on low molecular weight compounds, understanding of the target protein is essential when interpreting the results. In other words, drug design can not be done without understanding the three-dimensional structure of proteins. Therefore, it is good to read and learn books related to SBDD.

NOTE: Unfortunately I have not studied SBDD in books, so please tell someone good books

Furthermore, since SBDD deals with proteins, it is not necessary to concatenate it with chemoinformatics and bioinformatics. If you understand both in the framework of drug discovery, you will be able to think in more depth, so let's be able to do both. That is absolutely fun. link:https://www.amazon.co.jp/dp/4780909201/[DRY analysis books] and link:https://www.amazon.co.jp/dp/4297103192[information technology that supports life science data analysis] will surely help your career.

As mentioned in Chapter 6, quantum chemical calculation is important to understand protein-ligand interactions. In particular, the ability to interpret interactions based on quantum chemistry in future SBDDs can be stated to be essential. Without prejudice think link:https://www.amazon.co.jp/dp/4130625047/[about the chemical in orbit concept] - the basic quantum chemistry please read the like. If you're using link:https://www.msg.chem.iastate.edu/gamess/[Gamess], you'll be able to help the link:https://www.amazon.co.jp/dp/4061543881/[new version of Quantum Chemical Beginners' Manual]. At least save energy decomposition analisys, which will increase your ability to interpret calculations and contribute to your project. Furthermore, FMO is needless to say, but it is an indispensable tool, so understanding link:https://www.jstage.jst.go.jp/article/jccj/advpub/0/advpub_2014-0039/_pdf[each component] will help drug design more than that

==== Beyond the "end"

You can add more advanced content than this manual as a chapter. Please do PR. Add them to the contributor and specify the author at the beginning of the chapter.
